import React from 'react';
import Lottie from 'react-lottie';
import * as animationData from './lottie.json';
import './Cart.css';
import Animatedimage from './AnimatedImage';
import CartItems from './CartItems';
import { Link } from 'react-router-dom';
function Cart({
  totalItems,
  cart,
  handleUpdateCartQuantity,
  handleEmptyCart,
  handleRemoveFromCart,
}) {
  console.log(cart, 'my cart');
  const isEmpty = !cart.line_items;
  const EmptyCart = () => (
    <>
      <div className="empty-cart-container">
        <Animatedimage />
        <div className="empty-cart">
          <h3> It's empty here</h3>
          <p>Start shopping to add items to your bag</p>
        </div>
        <br />
        <Link to={'/'} style={{ textDecoration: 'none' }}>
          <button
            type="button"
            className="btn btn-home"
            style={{
              margin: '0 auto',
              outline: 'none',
              backgroundColor: '#F8DE4B',
              color: '#2766CC',
              border: '1px solid #F8DE4B',
              transition: 'all .3s ease-out',
              cursor: 'pointer',
            }}
          >
            Go to Homepage
          </button>
        </Link>
        <br />
      </div>
    </>
  );
  const FullCart = () => (
    <>
      {cart.line_items.map((item) => {
        return (
          <CartItems
            key={item.id}
            item={item}
            onUpdateCartQuantity={handleUpdateCartQuantity}
            onRemoveFromCart={handleRemoveFromCart}
          />
        );
      })}
      <div className="cart-results">
        <div className="container">
          <div className="cart-subtotal">
            <h4>subtotal</h4>
            <h4>{cart.subtotal.formatted_with_symbol}</h4>
          </div>
          <div className="cartDetials">
            <button
              type="button"
              className="btn btn-empty"
              onClick={handleEmptyCart}
            >
              empty cart
            </button>
            <button type="button" className="btn btn-checkout">
              checkout
            </button>
          </div>
        </div>
      </div>
    </>
  );

  <style type="text/css">/* generated by https://loading.io/ */</style>;
  if (!cart.line_items)
    return (
      <div class="loadingio-spinner-ripple-py13mrf51ab">
        <div class="ldio-pa08a6ii9i8">
          <div></div>
          <div></div>
        </div>
      </div>
    );
  return <>{!cart.line_items.length ? <EmptyCart /> : <FullCart />}</>;
}

export default Cart;
